---
title: "数据科学导论作业1215"
author: "Hongling Lei"
date: "12/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
data1.9 <- read.csv("data_povline1.9.csv")
data5.5 <- read.csv("data_povline5.5.csv")
data10 <- read.csv("data_povline10.csv")
```

### Poverty Comparisons: Using headcount to represent poverty level
```{r}
ggplot(data=data1.9, aes(x=RequestYear, y=HeadCount, color=CountryCode))+
  geom_line(size=0.5)+
  labs(title = "Poverty comparison with wealth level of $1.9/day")
```
```{r}
ggplot(data=data5.5, aes(x=RequestYear, y=HeadCount, color=CountryCode))+
  geom_line(size=0.5)+
  labs(title = "Poverty comparison with wealth level of $5.5/day")
```
```{r}
ggplot(data=data10, aes(x=RequestYear, y=HeadCount, color=CountryCode))+
  geom_line(size=0.5)+
  labs(title = "Poverty comparison with wealth level of $10/day")
```


### Inequality Comparisons: Using Gini to represent inequality
```{r}
ggplot(data=data1.9, aes(x=RequestYear, y=Gini, color=CountryCode))+
  geom_line(size=0.5)+
  labs(title = "Inequality comparison with wealth level of $1.9/day")
```
```{r}
ggplot(data=data5.5, aes(x=RequestYear, y=Gini, color=CountryCode))+
  geom_line(size=0.5)+
  labs(title = "Inequality comparison with wealth level of $5.5/day")
```

```{r}
ggplot(data=data10, aes(x=RequestYear, y=Gini, color=CountryCode))+
  geom_line(size=0.5)+
  labs(title = "Inequality comparison with wealth level of $10/day")
```